groups:
  - name: ServiceDown
    rules:
      - alert: InstanceDown
        expr: up{job="services"} < 1
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

# TODO: Find out which expr shold I use
#  - name: Errors
#    rules:
#      - alert: HighErrorRate (5xx)
#        expr: rate(echo_framework_rest_api_http_requests_count{status_code="500"}[1m]) / rate(echo_framework_rest_api_http_requests_count[1m]) > 0.1
#        for: 1s
#        labels:
#          severity: critical
#        annotations:
#          summary: "High error rate"
#          description: "{{ $labels.instance }} has a {{ $value }}% errors."
#
#      - alert: HighErrorRate (4xx)
#        expr: rate(echo_framework_rest_api_http_requests_count{status_code="400"}[1m]) / rate(echo_framework_rest_api_http_requests_count[1m]) > 0.05
#        for: 1s
#        labels:
#          severity: warning
#        annotations:
#          summary: "High error rate"
#          description: "{{ $labels.instance }} has a {{ $value }}% errors."
